### ISSUE TITLE
脚本好像突然失效了

### ISSUE THREAD

**Issue by cduang** [lovebai/xiaobei#13]
你好今天脚本好像突然失效了，重复运行仍然失败

**Comment by lovebai** [comment]
> 你好今天脚本好像突然失效了，重复运行仍然失败

xiaobei验证机制改了，现已修复，fetch upstream更新一下

**Comment by cduang** [comment]
> > 你好今天脚本好像突然失效了，重复运行仍然失败
> 
> xiaobei验证机制改了，现已修复，fetch upstream更新一下

感谢大佬，又可以愉快的自动打卡啦^_^

**Comment by lovebai** [comment]
closed.
