### ISSUE TITLE
Server酱

### ISSUE THREAD

**Issue by Begginm** [lovebai/xiaobei#15]
Server酱这个怎么Secrets进去啊，没看太懂

**Comment by lovebai** [comment]
server酱需要自行添加代码

**Comment by Begginm** [comment]
还有就是企业微信那个图片id还是没看明白怎么看出来的https://work.weixin.qq.com/wework_admin/material/getOpenMsgBuf?type=image&media_id=2xDBvOIHPvZrzzK_WQaevzb-htAZDFmYwgNKQnPG5Xms2VmwsybIWIBzxG6qOty-b&file_name=20210208142819.png&download=1 这是我那个图片的id我就找不到是那个

**Comment by lovebai** [comment]
> 还有就是企业微信那个图片id还是没看明白怎么看出来的https://work.weixin.qq.com/wework_admin/material/getOpenMsgBuf?type=image&media_id=2xDBvOIHPvZrzzK_WQaevzb-htAZDFmYwgNKQnPG5Xms2VmwsybIWIBzxG6qOty-b&file_name=20210208142819.png&download=1 这是我那个图片的id我就找不到是那个

您要的server酱给你弄上了，最后一次更新，打开这个网站https://sct.ftqq.com/，扫码登录，获取sendkey

**Comment by Begginm** [comment]
大佬，server酱的sendkey添加了但是现在签到不显示是什么情况。现在邮箱显示也没有了。然后我今天又再次重新录入sendkey也是不行

**Comment by lovebai** [comment]
消息通道里面使用并关注方糖服务号，或者提供以下日志截图 邮箱提示被干掉了

**Comment by Begginm** [comment]
![image](https://user-images.githubusercontent.com/63287239/156109844-ba68dadc-c4a3-4c83-8a86-9489eeef24c9.png)
方糖之前也就关注了，在smzdm自动签到上也能用。就是咱这个没效果

**Comment by lovebai** [comment]
> ![image](https://user-images.githubusercontent.com/63287239/156109844-ba68dadc-c4a3-4c83-8a86-9489eeef24c9.png) 方糖之前也就关注了，在smzdm自动签到上也能用。就是咱这个没效果
把邮箱那个去掉吧 我这边测试是没有问题的

**Comment by lovebai** [comment]
over.
