### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by zcmi** [lovebai/xiaobei#17]
在debian服务器上试了dev的脚本版和编译好的版本都不行，github action在第一步运行win编译好的版本也出了问题

<img width="839" alt="Snipaste_2022-02-27_11-25-53" src="https://user-images.githubusercontent.com/24654015/155866948-8e48fe15-1f88-4b06-96a3-d46a889d96d1.png">
<img width="394" alt="Snipaste_2022-02-27_11-25-38" src="https://user-images.githubusercontent.com/24654015/155866954-83ff5465-9570-44d1-83fa-9a095e7838bc.png">
<img width="536" alt="Snipaste_2022-02-27_11-24-16" src="https://user-images.githubusercontent.com/24654015/155866957-22e02f54-ce0d-46be-b613-94037b91d8ff.png">

**Comment by lovebai** [comment]
> 在debian服务器上试了dev的脚本版和编译好的版本都不行，github action在第一步运行win编译好的版本也出了问题
> 
> <img alt="Snipaste_2022-02-27_11-25-53" width="839" src="https://user-images.githubusercontent.com/24654015/155866948-8e48fe15-1f88-4b06-96a3-d46a889d96d1.png">
> 
> <img alt="Snipaste_2022-02-27_11-25-38" width="394" src="https://user-images.githubusercontent.com/24654015/155866954-83ff5465-9570-44d1-83fa-9a095e7838bc.png">
> 
> <img alt="Snipaste_2022-02-27_11-24-16" width="536" src="https://user-images.githubusercontent.com/24654015/155866957-22e02f54-ce0d-46be-b613-94037b91d8ff.png">

dev 和release 都不可以在正常运行 使用main中的吧

**Comment by lovebai** [comment]
closed.
