### ISSUE TITLE
请问如何让它更早打卡呢

### ISSUE THREAD

**Issue by miyuren** [lovebai/xiaobei#19]
如标题所言，我这里显示11点作用才打的卡，求问大佬控制打卡时间的命令在哪一行

**Comment by lovebai** [comment]
> 如标题所言，我这里显示11点作用才打的卡，求问大佬控制打卡时间的命令在哪一行

修改.github/workflows/python-app.yml文件中的schedule参数即可

**Comment by miyuren** [comment]
感谢大佬解答，但是我最近的打卡都失效了，不知道是不是接口问题，大佬你的打卡脚本还能正常运行吗？

**Comment by coco-Z** [comment]
我想要每天早上8点运行，怎么设置？

**Comment by lovebai** [comment]
> 我想要每天早上8点运行，怎么设置？

修改.github/workflows/python-app.yml文件中的schedule参数即可，时间参考这个文章
https://blog.csdn.net/xsm666/article/details/110085666
