### ISSUE TITLE
Actions在执行Set Up Python时出错

### ISSUE THREAD

**Issue by Pems002** [lovebai/xiaobei#20]
不会提PR所以就放在issues里了，
官方在Setup Python里使用的是如图的：

<img width="370" alt="image" src="https://user-images.githubusercontent.com/29890309/161169725-b81b4829-3145-49ff-9696-fc99c4b728b3.png">

所以只需要更改29行就不会报错了
` uses: actions/setup-python@master` -> `uses: actions/setup-python@v3.0.0`
不是很懂这个所以如果有错请忽略！

**Comment by lovebai** [comment]
> 不会提PR所以就放在issues里了， 官方在Setup Python里使用的是如图的：
> 
> <img alt="image" width="370" src="https://user-images.githubusercontent.com/29890309/161169725-b81b4829-3145-49ff-9696-fc99c4b728b3.png">
> 
> 所以只需要更改29行就不会报错了 ` uses: actions/setup-python@master` -> `uses: actions/setup-python@v3.0.0` 不是很懂这个所以如果有错请忽略！

感谢提供方案💐，这个问题是今天才出现的，问题已解决
