### ISSUE TITLE
本地打卡失败；建议后期增加多账户运行

### ISSUE THREAD

**Issue by 133077787** [lovebai/xiaobei#21]
![image](https://user-images.githubusercontent.com/49564600/161214841-3ddb7d75-6e65-4de5-85ef-465b2b204384.png)

**Comment by lovebai** [comment]
> ![image](https://user-images.githubusercontent.com/49564600/161214841-3ddb7d75-6e65-4de5-85ef-465b2b204384.png)

本地脚本有问题，很久没更新了，勿用

**Comment by WangHan2014** [comment]
已经实现了
