### ISSUE TITLE
位置问题

### ISSUE THREAD

**Issue by lzc8890** [lovebai/xiaobei#9]
第一次设置位置是对的，在想修改位置不生效，没有吗解决办法？

**Comment by lovebai** [comment]
> 第一次设置位置是对的，在想修改位置不生效，没有吗解决办法？
可以直接设置`XB_COORD` 环境变量     列如：中国-云南省-昆明市-官渡区 或者根据之前打卡的区域来，可以看小北之前打打卡记录，如需修改位置在secrets下的update对应的变量参数，每天只能打卡一次 如当日已打 修改后次日生效

**Comment by lzc8890** [comment]
谢谢，还有请问一下经纬度的变量也要更新吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月15日(周三) 下午5:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lovebai/xiaobei] 位置问题 (#9)




  
第一次设置位置是对的，在想修改位置不生效，没有吗解决办法？
 可以直接设置XB_COORD 环境变量     列如：中国-云南省-昆明市-官渡区 或者根据之前打卡的区域来，可以看小北之前打打卡记录，如需修改位置在secrets下的update对应的变量参数，每天只能打卡一次 如当日已打 修改后次日生效

**Comment by lovebai** [comment]
> 谢谢，还有请问一下经纬度的变量也要更新吗？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年9月15日(周三) 下午5:03 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [lovebai/xiaobei] 位置问题 (#9) 第一次设置位置是对的，在想修改位置不生效，没有吗解决办法？ 可以直接设置XB_COORD 环境变量 列如：中国-云南省-昆明市-官渡区 或者根据之前打卡的区域来，可以看小北之前打打卡记录，如需修改位置在secrets下的update对应的变量参数，每天只能打卡一次 如当日已打 修改后次日生效 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

一般情况下，只用设置经纬度就可以了 ，更新或者不更新都可以
